name       : haskell-extensible-exceptions
version    : 0.1.1.4
release    : 2
source     :
    - https://hackage.haskell.org/package/extensible-exceptions-0.1.1.4/extensible-exceptions-0.1.1.4.tar.gz : 6ce5e8801760385a408dab71b53550f87629e661b260bdc2cd41c6a439b6e388
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides extensible exceptions for both new and old versions
    of GHC (i.e., < 6.10).
description: |
    This package provides extensible exceptions for both new and old versions of GHC (i.e., < 6.10).
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
